If an exception has occurred. The method creates an Object known.